### PR TITLE
upgrade winston

### PR DESCRIPTION
**Pull request by juan-coralogix**
Upgraded Winston version.

### CODE REVIEW

**Review by talknopf — CHANGES_REQUESTED** [review]
Please change the author to support@coralogix.com

**Comment by talknopf** [comment]
@juan-coralogix please be sure to test as well.

**Comment by juan-coralogix** [comment]
> Please change the author to [support@coralogix.com](mailto:support@coralogix.com)

Changed to support.
Also tested

**Review by talknopf — APPROVED** [review]

**Comment by patolit** [comment]
this breaks integration if used in my codebase version 2.7 of Winston. 

this change as is not backward compatible should increase the major version in package JSON and not minor

**Pull request merged**
