### PR TITLE
TES-4800 allow exposing waitForFlush capability

### PR DESCRIPTION
**Pull request by benjamingr**
Hey,

As discussed on email.

 - I added a test to help you accept the code. I tried running the linter but it did not pass on master.  I made sure not to introduce any _new_ lint issues.
 - I noticed dist is committed so I ran a build - I would recommend removing it from the repo as it is derived from the source.

Cheers and love,
Benji and Moshe

### CODE REVIEW

**Comment by oded-dd** [comment]
# [Codecov](https://codecov.io/gh/coralogix/nodejs-coralogix-sdk/pull/15?src=pr&el=h1) Report
> Merging [#15](https://codecov.io/gh/coralogix/nodejs-coralogix-sdk/pull/15?src=pr&el=desc) into [master](https://codecov.io/gh/coralogix/nodejs-coralogix-sdk/commit/5eead7747223d61acd5d4c5cfd0a7ed1b2ba8826&el=desc) will **decrease** coverage by `17.98%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/coralogix/nodejs-coralogix-sdk/pull/15?src=pr&el=tree)

```diff
@@             Coverage Diff             @@
##           master      #15       +/-   ##
===========================================
- Coverage   93.77%   75.79%   -17.99%     
===========================================
  Files          12       12               
  Lines         241      252       +11     
===========================================
- Hits          226      191       -35     
- Misses         15       61       +46     
```


| [Impacted Files](https://codecov.io/gh/coralogix/nodejs-coralogix-sdk/pull/15?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [dist/entities/LoggerConfig.js](https://codecov.io/gh/coralogix/nodejs-coralogix-sdk/pull/15/diff?src=pr&el=tree#diff-ZGlzdC9lbnRpdGllcy9Mb2dnZXJDb25maWcuanM=) | `33.33% <0.00%> (-66.67%)` | :arrow_down: |
| [dist/entities/bulk.js](https://codecov.io/gh/coralogix/nodejs-coralogix-sdk/pull/15/diff?src=pr&el=tree#diff-ZGlzdC9lbnRpdGllcy9idWxrLmpz) | `40.00% <0.00%> (-60.00%)` | :arrow_down: |
| [dist/http.service.js](https://codecov.io/gh/coralogix/nodejs-coralogix-sdk/pull/15/diff?src=pr&el=tree#diff-ZGlzdC9odHRwLnNlcnZpY2UuanM=) | `42.10% <0.00%> (-57.90%)` | :arrow_down: |
| [dist/entities/buffer.action.js](https://codecov.io/gh/coralogix/nodejs-coralogix-sdk/pull/15/diff?src=pr&el=tree#diff-ZGlzdC9lbnRpdGllcy9idWZmZXIuYWN0aW9uLmpz) | `60.00% <0.00%> (-40.00%)` | :arrow_down: |
| [dist/debug.logger.js](https://codecov.io/gh/coralogix/nodejs-coralogix-sdk/pull/15/diff?src=pr&el=tree#diff-ZGlzdC9kZWJ1Zy5sb2dnZXIuanM=) | `63.63% <0.00%> (-36.37%)` | :arrow_down: |
| [dist/entities/logs.buffer.js](https://codecov.io/gh/coralogix/nodejs-coralogix-sdk/pull/15/diff?src=pr&el=tree#diff-ZGlzdC9lbnRpdGllcy9sb2dzLmJ1ZmZlci5qcw==) | `71.42% <0.00%> (-28.58%)` | :arrow_down: |
| [dist/helpers/rx.helper.js](https://codecov.io/gh/coralogix/nodejs-coralogix-sdk/pull/15/diff?src=pr&el=tree#diff-ZGlzdC9oZWxwZXJzL3J4LmhlbHBlci5qcw==) | `85.71% <0.00%> (-14.29%)` | :arrow_down: |
| [dist/entities/log.js](https://codecov.io/gh/coralogix/nodejs-coralogix-sdk/pull/15/diff?src=pr&el=tree#diff-ZGlzdC9lbnRpdGllcy9sb2cuanM=) | `87.87% <0.00%> (-12.13%)` | :arrow_down: |
| [dist/helpers/ip.helper.js](https://codecov.io/gh/coralogix/nodejs-coralogix-sdk/pull/15/diff?src=pr&el=tree#diff-ZGlzdC9oZWxwZXJzL2lwLmhlbHBlci5qcw==) | `68.42% <0.00%> (-10.53%)` | :arrow_down: |
| [dist/logger.manager.js](https://codecov.io/gh/coralogix/nodejs-coralogix-sdk/pull/15/diff?src=pr&el=tree#diff-ZGlzdC9sb2dnZXIubWFuYWdlci5qcw==) | `82.08% <0.00%> (-1.84%)` | :arrow_down: |

------

[Continue to review full report at Codecov](https://codecov.io/gh/coralogix/nodejs-coralogix-sdk/pull/15?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/coralogix/nodejs-coralogix-sdk/pull/15?src=pr&el=footer). Last update [5eead77...f0f344e](https://codecov.io/gh/coralogix/nodejs-coralogix-sdk/pull/15?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by benjamingr** [comment]
This PR addresses an issue where logs are dropped if the Node server is shut-down by exposing an API letting coralogix-logger wait for logs to be sent from the backend.

The original issue is very easy to reproduce. You can call:

```
tester.addDemoLine();
process.exit();
```

In tester.ts to see that it's not sent to the backend :]

**Comment by benjamingr** [comment]
Hey, this was supposed to be merged a month ago. You said "3-4" weeks - any update?

**Comment by benjamingr** [comment]
Ping? Another month has passed

**Review by amnons77 — APPROVED** [review]

**Review by amnons77 — APPROVED** [review]

**Review by amnons77 — APPROVED** [review]

**Review by amnons77 — APPROVED** [review]

**Comment by benjamingr** [comment]
Ok, @amnons77 I feel like your company is friends with my company so the charitable thing would be to give out free advice from a Node core team member who also maintains several open source libraries and [breaks stuff myself](https://github.com/benjamingr/tmp-promise/issues/43) all the time.

For what it's worth, the way this logger is written isn't how you're supposed to write loggers for Node.js.

Even if you remove all the deprecated and old APIs the code uses (like request and rxjs) and how much it actually needs those dependencies for (it doesn't, it can be significantly shorter without them) - there are fundamental issues namely:

 - A logger is fundamentally infrastructure, I shouldn't feel it in my code.
 - A logger should have few or zero dependencies.
 - Unless logging can be as fast and reliable as writing to a stream, a logger should read from stdout and write to an endpoint.
 - Things like "logs get to their target" is not a luxury feature. Waiting for an interval before terminating is not an acceptable solution to that. Logs are critical for root cause analysis.
 - I'm not even talking about expecting the logger to understand my code. I assume the Java version understands the function and method name it's coming from (I see fields for that). Other loggers understand source maps and basic code structure. Since coralogix runs on elasticsearch, you could just "steal" the [code from elastic](https://github.com/elastic/apm-agent-nodejs/) if you need to add support.

There are also some quick wins you can do, probably use a [reasonably fast](https://www.npmjs.com/package/sonic-boom) library for writing stuff and a [reasonably fast](https://www.npmjs.com/package/fast-safe-stringify) JSON library. Those are dependencies that would actually be justified IMO.

If you start with `pino`/`pino-http` that would probably be a good starting point :]

**Pull request merged**
